# This is a basic workflow to help you get started with Actions

name: wf01

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
              
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Starting the steps in the build job!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 3
          echo 2
          echo 1
          
      - name: Install dependencies
        run: |
          make install

      - name: lint_with_flake8
        run: |
          make lint
          #fail_on_error: true
          #lint_with_pylint_flags: '--no-exit-on-warn --no-exit-on-error'
        
      - name: Test with Pytest
        run: |
          make test

      - name: Format code with Python black
        run: |
          make format
